name: Coffee break
on:
  schedule:
    - cron: '50 7/3 26 8 *'
    - cron: '50 1/3 27 8 *'
    - cron: '50 1,4 28 8 *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: curl -X POST "$SLACK_WEBHOOK"
      env: 
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
